version: '3'
services:
  cypress:
    image: cypress/included:3.7.0
    depends_on: 
      - web
    working_dir: /e2e/test-server
    volumes:
      - ../:/e2e
    environment: 
      - CYPRESS_BASE_URL=http://web/cypress-mh-tests/
      - CYPRESS_mailHogUrl=http://mailhog:8025